In [2]:
# TensorFlow, an open-source machine learning framework, primarily uses tensors as its fundamental data structure. Tensors are multi-dimensional arrays used to represent data.
# Tensor:
# Tensors are the primary data structure in TensorFlow, representing multi-dimensional arrays.
# Variable:
# TensorFlow Variables are used to store and update trainable parameters, such as weights and biases in a neural network.
# SparseTensor:
# TensorFlow supports sparse tensors for representing tensors with a large number of zero values efficiently.

In [3]:
# # in TensorFlow, both constants and variables are used to represent and store data, but they have different purposes and characteristics.
# # TensorFlow Constant:
# # A TensorFlow constant is a type of tensor whose value cannot be changed once it is assigned. It is used to represent fixed values in a TensorFlow graph. Once you define a constant, its value remains the same throughout the execution of the program.
# # TensorFlow Variable:
# # A TensorFlow variable, on the other hand, is a type of tensor whose value can be changed during the execution of a program. Variables are typically used to store and update model parameters like weights and biases during training.
# Constant: Immutable, its value cannot be changed after creation.
# Variable: Mutable, its value can be changed during the execution of the program, making it suitable for parameters that need to be updated during training.

In [5]:
# Matrix Addition:
# Matrix addition is a simple operation where corresponding elements of two matrices are added together to produce a new matrix with the same dimensions. In TensorFlow, you can use the tf.add function for matrix addition.
import tensorflow as tf
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result_addition = tf.add(matrix_a, matrix_b)
# Matrix Multiplication:
# Matrix multiplication is a more complex operation where the dot product of rows and columns is computed to produce a new matrix.
result_multiplication = tf.matmul(matrix_a, matrix_b)
# Element-wise Operations:
# Element-wise operations involve performing a specific operation on each corresponding element of two matrices or a single matrix. Common element-wise operations include addition, subtraction, multiplication, and division. TensorFlow supports these operations directly.
result_elementwise_mul = tf.multiply(matrix_a, matrix_b)
print("Element-wise Multiplication Result:")
print(result_elementwise_mul.numpy())
print("Matrix Addition Result:")
print(result_addition.numpy())
print("Matrix Multiplication Result:")
print(result_multiplication.numpy())

Element-wise Multiplication Result:
[[ 5 12]
 [21 32]]
Matrix Addition Result:
[[ 6  8]
 [10 12]]
Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [21]:
matrix_a = tf.cast(tf.random.normal(shape=(2, 2), mean=0, stddev=1), dtype=tf.float32)
print("Matrix A:")
print(matrix_a.numpy())
x = 2
matrix_B = tf.random.truncated_normal(shape=(x, x), mean=0, stddev=1)
print("\nMatrix B:")
print(matrix_B.numpy())
matrix_c = tf.random.normal(shape=(2, 2), mean=3, stddev=0.5)
print("\nMatrix C:")
print(matrix_c.numpy())
matrix_d = matrix_a + matrix_B
print("\nMatrix D (Result of Addition):")
print(matrix_d.numpy())
matrix_e = tf.matmul(matrix_c,matrix_d)
print(matrix_e.numpy())

Matrix A:
[[ 0.6217819  -0.35800076]
 [-0.8292485   1.0875517 ]]

Matrix B:
[[-0.4569535  -0.9830455 ]
 [-1.7080914  -0.86306626]]

Matrix C:
[[2.7113526 3.3097386]
 [3.507611  2.2790608]]

Matrix D (Result of Addition):
[[ 0.16482839 -1.3410463 ]
 [-2.53734     0.22448546]]
[[-7.951024  -2.8930614]
 [-5.204598  -4.192253 ]]


In [31]:
mat_f = tf.random.uniform(shape=(3, 3), minval=0, maxval=10)
print("Matrix F:")
print(mat_f.numpy())

# Transpose matrix F to create matrix G
mat_g = tf.transpose(mat_f)
print("\nMatrix G (Transpose of Matrix F):")
print(mat_g.numpy())

# Calculate the element-wise exponential of matrix F to create matrix H
mat_h = tf.exp(mat_f)
print("\nMatrix H (Element-wise Exponential of Matrix F):")
print(mat_h.numpy())

# Concatenate matrix F and its transpose along axis 1 to create matrix I
mat_i = tf.concat(values=[mat_f, mat_g], axis=1)
print("\nMatrix I (Concatenation of Matrix F and its Transpose along Axis 1):")
print(mat_i.numpy())

# Concatenate matrix F and its transpose along axis 0 to create matrix J
mat_j = tf.concat(values=[mat_f, mat_g], axis=0)
print("\nMatrix J (Concatenation of Matrix F and its Transpose along Axis 0):")
print(mat_j.numpy())

Matrix F:
[[2.200358   2.033645   2.8424072 ]
 [6.5518427  0.50438523 3.003136  ]
 [9.341659   3.2461202  2.0447958 ]]

Matrix G (Transpose of Matrix F):
[[2.200358   6.5518427  9.341659  ]
 [2.033645   0.50438523 3.2461202 ]
 [2.8424072  3.003136   2.0447958 ]]

Matrix H (Element-wise Exponential of Matrix F):
[[9.0282440e+00 7.6418896e+00 1.7157017e+01]
 [7.0053387e+02 1.6559671e+00 2.0148623e+01]
 [1.1403306e+04 2.5690472e+01 7.7275801e+00]]

Matrix I (Concatenation of Matrix F and its Transpose along Axis 1):
[[2.200358   2.033645   2.8424072  2.200358   6.5518427  9.341659  ]
 [6.5518427  0.50438523 3.003136   2.033645   0.50438523 3.2461202 ]
 [9.341659   3.2461202  2.0447958  2.8424072  3.003136   2.0447958 ]]

Matrix J (Concatenation of Matrix F and its Transpose along Axis 0):
[[2.200358   2.033645   2.8424072 ]
 [6.5518427  0.50438523 3.003136  ]
 [9.341659   3.2461202  2.0447958 ]
 [2.200358   6.5518427  9.341659  ]
 [2.033645   0.50438523 3.2461202 ]
 [2.8424072  3.003136  